//import TokenLogin from "../component/login/TokenLogin";
import { APPLICATION_ROUTES, APP_ROLE } from "../utils/constants";

import {
  // AdGroupReport,
  // CAMPAIGNTABLEComponent,
  // CREATIVEREPORT,
  DASHBOARDComponent,
  // FLIPKARTCAMPAIGNComponent,
  // CAMPAIGNLIVE,
  // FLIPKARTComponent,
  // FLIPKARTREPORTCAMPAIGNComponent,
  // FLIPKARTRULES,
  // FSNReport,
  // AMAZONSEARCHREPORT,
  // AMAZONCAMPAIGN,
  // AMAZONADGROUP,
  // KEYWORDREPORT,
  // NEGATIVEKEYWORD,
  // PLACEMENTREPORT,
  // REVENUEREPORT,
  // SEARCHREPORT,
  // SEARCHTERM,
  // TARGETREPORT,
  // CREATENEWCAMPAIGN,
  // BLINKITComponent,
  // BUDGETTREND,
  // EDITCAMPAIGN,
  // BLINKITCAMPAIGNComponent,
  // BLINKITREPORTCAMPAIGNComponent,
  // BLINKITCATEGORYREPORT,
  // BLINKITKEYWORDREPORT,
  // BLINKITSEARCHREPORT,
  // BLINKITPLACEMENTREPORT,
  // BLINKITFSNREPORT,
  // BLINKITREVENUEREPORT,
  // AMAZONAMS,
  // AMAZONADVERTISE,
  // BLINKITCREATENEWCAMPAIGN,
  // BLINKITNEGATIVEKEYWORD,
  // ACTIONACTIVITY,
  // AMAZONACTIONACTIVITY,
  // AMAZONBUDGETPACER,
  // AMAZONNEGATIVEKEYWORD,
  // AMAZONSEARCHTERM,
  // AMSCREATENEWCAMPAIGN,
  // AMAZONRULES,
  // AMAZONCREATIVEREPORT,
  // AMAZONPLACEMENTREPORT,
  // AMAZONASINREPORT,
  // AMAZONPORTFOLIOREPORT,
  // AMSMETRICANALYZER,
  // COMMONSCREENComponent,
  // AMSCREATEBulkNEWCAMPAIGN,
  // ZEPTOComponent,
  // ZEPTOCATEGORYREPORT,
  // ZeptoCAMPAIGNComponent,
  // ZEPTOCAMPAIGNREPORT,
  // ZEPTOKEYWORDREPORT,
  // ZEPTOPRODUCTREPORT,
  // ZEPTOACTIONACTIVITY,
  // BLINKITACTIONACTIVITY,
  //
  // BLINKITEDITCAMPAIGN,
  // COMMONCATALOG,
  // AMSCREATEBulkNEWAGROUPCAMPAIGN,
  // ZEPTOCREATENEWCAMPAIGN,
  // ZEPTOBUDGETPACER,
  // BLINKITRULES,
  // ZEPTORULES,
  // BLINKITBUDGETPACER,
  // INSTAMART,
  // INSTAMART_CAMPAIGN,
  // INSTAMART_CAMPAIGN_REPORT,
  // INSTAMART_KEYWORD,
  // INSTAMART_PRODUCT_REPORT,
  // INSTAMART_ACTION_ACTIVITY,
  // INSTAMART_BUDGET_PACER,
  // INSTAMARTRULES,
  // INSTAMARTCREATENEWCAMPAIGN,
  // INSTAMARTEDITCAMPAIGN,
  // INSTAMARTDUPLICATENEWCAMPAIGN,
  // CustomReportSetting,

  // CUSTOM REPORT
  // CUSTOMREPORT, //custom REport
  // TAGMANAGER,
  // CREATEMASTER,
  // PRICINGRULEENGINE,
  // ALERTCONTROL,
  // GLOBALVIEW,
  // USERONBOARD, //USER ONBOARD
  // CREATEPASSWORD,
  // UNAUTHORIZED,
  // EbuxComponent,
  // EbuxWidgetComponent,
  // WeightedSOSPage
} from "./dynaminRoutes";

// const amazonRoutes = [{
//   routePath: APPLICATION_ROUTES.AMAZONCAMPAING,
//   component: CAMPAIGNTABLEComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONACTIONACTIVITY,
//   component: AMAZONACTIONACTIVITY,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },{
//   routePath: APPLICATION_ROUTES.AMAZONBUDGETPACER,
//   component: AMAZONBUDGETPACER,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONASINREPORT,
//   component: AMAZONASINREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONPORTFOLIOREPORT,
//   component: AMAZONPORTFOLIOREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.AMAZONAMS,
//   component: AMAZONAMS,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONRULES,
//   component: AMAZONRULES,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONADVERTISE,
//   component: AMAZONADVERTISE,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// //!-----------
// {
//   routePath: APPLICATION_ROUTES.AMAZONCREATIVEREPORT,
//   component: AMAZONCREATIVEREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.AMAZONPLACEMENTREPORT,
//   component: AMAZONPLACEMENTREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.AMAZONNEGATIVEKEYWORD,
//   component: AMAZONNEGATIVEKEYWORD,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONSEARCHTERM,
//   component: AMAZONSEARCHTERM,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONSEARCHREPORT,
//   component: AMAZONSEARCHREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONCAMPAIGN,
//   component: AMAZONCAMPAIGN,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMAZONADGROUP,
//   component: AMAZONADGROUP,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.AMAZONBUDGETPACER,
//   component: AMAZONBUDGETPACER,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.KEYWORDREPORT,
//   component: KEYWORDREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMSCREATENEWCAMPAIGN,
//   component: AMSCREATENEWCAMPAIGN,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },
// {
//   routePath: APPLICATION_ROUTES.AMSCREATEBULKCAMPAIGN,
//   component: AMSCREATEBulkNEWCAMPAIGN,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },

// {
//   routePath: APPLICATION_ROUTES.AMSMETRICANALYZER,
//   component: AMSMETRICANALYZER,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/amazon",
// },];
// const blinkitRoutes = [{
//   routePath: APPLICATION_ROUTES.BLINKIT,
//   component: BLINKITComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },{
//   routePath: APPLICATION_ROUTES.BLINKIT,
//   component: BLINKITComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKIT,
//   component: BLINKITComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITCAMPAING,
//   component: BLINKITCAMPAIGNComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITNEGATIVEKEYWORD,
//   component: BLINKITNEGATIVEKEYWORD,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITREPORTCAMPAING,
//   component: BLINKITREPORTCAMPAIGNComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITCATEGORYREPORT,
//   component: BLINKITCATEGORYREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// // {
// //   routePath: APPLICATION_ROUTES.BLINKITREPORTTARGET,
// //   component: BLINKITTARGETREPORT,
// //   isPrivate: true,
// //   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
// //   visibleAfterLogin: true,
// //   sidebar: "/blinkit",
// // },
// {
//   routePath: APPLICATION_ROUTES.BLINKITKEYWORDREPORT,
//   component: BLINKITKEYWORDREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// // {
// //   routePath: APPLICATION_ROUTES.BLINKITCREATIVEREPORT,
// //   component: BLINKITCREATIVEREPORT,
// //   isPrivate: true,
// //   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
// //   visibleAfterLogin: true,
// //   sidebar: "/blinkit",
// // },
// {
//   routePath: APPLICATION_ROUTES.BLINKITREVENUEREPORT,
//   component: BLINKITREVENUEREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITCREATENEWCAMPAIGN,
//   component: BLINKITCREATENEWCAMPAIGN,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },

// {
//   routePath: APPLICATION_ROUTES.BLINKITFSNREPORT,
//   component: BLINKITFSNREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITSEARCHREPORT,
//   component: BLINKITSEARCHREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITPLACEMENTREPORT,
//   component: BLINKITPLACEMENTREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },
// {
//   routePath: APPLICATION_ROUTES.BLINKITACTIONACTIVITY,
//   component: BLINKITACTIONACTIVITY,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/blinkit",
// },];
// const zeptoRoutes = [ {
//   routePath: APPLICATION_ROUTES.ZEPTO,
//   component: ZEPTOComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOCATEGORYREPORT,
//   component: ZEPTOCATEGORYREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOCAMPAIGNREPORT,
//   component: ZEPTOCAMPAIGNREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOKEYWORDREPORT,
//   component: ZEPTOKEYWORDREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOCAMPAING,
//   component: ZeptoCAMPAIGNComponent,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOPRODUCTREPORT,
//   component: ZEPTOPRODUCTREPORT,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// },
// {
//   routePath: APPLICATION_ROUTES.ZEPTOACTIONACTIVITY,
//   component: ZEPTOACTIONACTIVITY,
//   isPrivate: true,
//   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   visibleAfterLogin: true,
//   sidebar: "/zepto",
// }];


// const getActiveClientProject = () =>
//   JSON.parse(localStorage.getItem("active_client_project")) || {};

// let availableRoutes = [
//   {
//     routePath: APPLICATION_ROUTES.EbuxOSA,
//     component: COMMONSCREENComponent,
//     // component: (props) => <EbuxComponent {...props} kpi="OSA" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.EbuxSOS,
//     component: (props) => <EbuxComponent {...props} kpi="SOS" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },
//   {
//     routePath: APPLICATION_ROUTES.EbuxSOM,
//     component: (props) => <EbuxComponent {...props} kpi="SOM" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.EbuxOR,
//     component: (props) => <EbuxComponent {...props} kpi="OR" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.EbuxCS,
//     component: (props) => <EbuxComponent {...props} kpi="CS" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.EbuxPRO,
//     component: (props) => <EbuxComponent {...props} kpi="PRO" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.EbuxRR,
//     component: (props) => <EbuxComponent {...props} kpi="RR" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },
//   {
//     routePath: APPLICATION_ROUTES.EbuxSOD,
//     component: (props) => <EbuxComponent {...props} kpi="SOD" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },


//   {
//     routePath: APPLICATION_ROUTES.COMMONSCREEN,
//     // component: COMMONSCREENComponent,

//     component: (props) => <EbuxComponent {...props} kpi="OSA" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },
//   {
//     routePath: APPLICATION_ROUTES.EbuxWidget,
//     // component: COMMONSCREENComponent,

//     component: (props) => <EbuxWidgetComponent {...props} kpi="OSA" />,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.TAGMANAGER,
//     component: TAGMANAGER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },
//   {
//     routePath: APPLICATION_ROUTES.CREATEMASTER,
//     component: CREATEMASTER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.globalView ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.CREATEMASTERCATEGORY,
//     component: CREATEMASTER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.globalView ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.PRICINGRULEENGINE,
//     component: PRICINGRULEENGINE,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.isPricingRuleEngine ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.PRICINGRULEENGINESUBPAGE,
//     component: PRICINGRULEENGINE,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.isPricingRuleEngine ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.ALERTCONTROL,
//     component: ALERTCONTROL,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.useAlerts ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.ALERTCONTROLSUBPAGE,
//     component: ALERTCONTROL,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     blockForClient: !(getActiveClientProject()?.useAlerts ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.GLOBALVIEW,
//     component: GLOBALVIEW,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     // headerFilter:false,
//     blockForClient: !(getActiveClientProject()?.globalView ?? false)
//   },
//   {
//     routePath: APPLICATION_ROUTES.WeightedSOS,
//     component: WeightedSOSPage,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     headerFilter:false,
//     showHeaderCalender: false,
//     blockForClient: !(getActiveClientProject()?.useWeightedSOS ?? false)
//   },



//   // {
//   //   routePath: APPLICATION_ROUTES.COMMONSCREEN,
//   //   component: COMMONSCREENComponent,
//   //   isPrivate: true,
//   //   accessRoles: [
//   //     APP_ROLE.ADMIN,
//   //     APP_ROLE.OWNER,
//   //     APP_ROLE.ANALYST,
//   //     APP_ROLE.MANAGER,
//   //   ],
//   //   visibleAfterLogin: true,
//   //   sidebar: "/dashboard",
//   // },
//   {
//     routePath: APPLICATION_ROUTES.COMMONCATALOG,
//     component: COMMONCATALOG,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   //USER ONBOARD
//   {
//     routePath: APPLICATION_ROUTES.USERONBOARD,
//     component: USERONBOARD,
//     isPrivate: true,
//     accessRoles: [APP_ROLE.ADMIN, APP_ROLE.OWNER],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },

//   {
//     routePath: APPLICATION_ROUTES.UN_AUTHORISED,
//     component: UNAUTHORIZED,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//   },
//   {
//     routePath: APPLICATION_ROUTES.CREATEPASSWORD,
//     component: CREATEPASSWORD,
//     isPrivate: false,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: false,
//     sidebar: "/dashboard",
//     // sidebar: "/flipkart",
//   },
//   //
//   {
//     routePath: APPLICATION_ROUTES.DASHBOARD,
//     component: DASHBOARDComponent,
//     isPrivate: false,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.TOKEN_LOGIN,
//     component: TokenLogin,
//     isPrivate: false,
//     accessRoles: [APP_ROLE.ALL],
//     visibleAfterLogin: true,
//     sidebar: "/dashboard",
//     // sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.CAMPAIGNLIVE,
//     component: CAMPAIGNLIVE,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKART,
//     component: FLIPKARTComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTO,
//     component: ZEPTOComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKIT,
//     component: BLINKITComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONAMS,
//     component: AMAZONAMS,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKART,
//     component: FLIPKARTComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTCAMPAING,
//     component: FLIPKARTCAMPAIGNComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTREPORTCAMPAING,
//     component: FLIPKARTREPORTCAMPAIGNComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.NEGATIVEKEYWORD,
//     component: NEGATIVEKEYWORD,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.SEARCHTERM,
//     component: SEARCHTERM,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTADGROUPREPORTCAMPAING,
//     component: AdGroupReport,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FSNREPORT,
//     component: FSNReport,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTTARGETREPORT,
//     component: TARGETREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTSEARCHREPORT,
//     component: SEARCHREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.PLACEMENTREPORT,
//     component: PLACEMENTREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.CREATIVEREPORT,
//     component: CREATIVEREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.REVENUEREPORT,
//     component: REVENUEREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTRULES,
//     component: FLIPKARTRULES,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.CREATENEWCAMPAIGN,
//     component: CREATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.EDITCAMPAIGN,
//     component: EDITCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITEDITCAMPAIGN,
//     component: BLINKITEDITCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BUDGETTREND,
//     component: BUDGETTREND,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ACTIONACTIVITY,
//     component: ACTIONACTIVITY,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONCAMPAING,
//     component: CAMPAIGNTABLEComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONACTIONACTIVITY,
//     component: AMAZONACTIONACTIVITY,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONBUDGETPACER,
//     component: AMAZONBUDGETPACER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONASINREPORT,
//     component: AMAZONASINREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONPORTFOLIOREPORT,
//     component: AMAZONPORTFOLIOREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },

//   {
//     routePath: APPLICATION_ROUTES.AMAZONAMS,
//     component: AMAZONAMS,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONRULES,
//     component: AMAZONRULES,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONADVERTISE,
//     component: AMAZONADVERTISE,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   //!-----------
//   {
//     routePath: APPLICATION_ROUTES.AMAZONCREATIVEREPORT,
//     component: AMAZONCREATIVEREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },

//   {
//     routePath: APPLICATION_ROUTES.AMAZONPLACEMENTREPORT,
//     component: AMAZONPLACEMENTREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },

//   {
//     routePath: APPLICATION_ROUTES.AMAZONNEGATIVEKEYWORD,
//     component: AMAZONNEGATIVEKEYWORD,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONSEARCHTERM,
//     component: AMAZONSEARCHTERM,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONSEARCHREPORT,
//     component: AMAZONSEARCHREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONCAMPAIGN,
//     component: AMAZONCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONADGROUP,
//     component: AMAZONADGROUP,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   // CUSTOM REPORT
//   {
//     routePath: APPLICATION_ROUTES.AMAZONCUSTOMREPORT,
//     component: CUSTOMREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMAZONCUSTOMREPORTBLANK,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   // BLINKIT CUSTOM REpORT
//   {
//     routePath: APPLICATION_ROUTES.BLINKITCUSTOMREPORT,
//     component: CUSTOMREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITCUSTOMREPORTBLANK,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITEDITREPORT,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },

//   // FLIPKART CUSTOM REPORT
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTCUSTOMREPORT,
//     component: CUSTOMREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTCUSTOMREPORTBLANK,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.FLIPKARTEDITREPORT,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/flipkart",
//   },

//   // INSTAMART CUSTOM REpORT
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTCUSTOMREPORT,
//     component: CUSTOMREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTCUSTOMREPORTBLANK,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTEDITREPORT,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },

//   //

//   // INSTAMART CUSTOM REpORT
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCUSTOMREPORT,
//     component: CUSTOMREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCUSTOMREPORTBLANK,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOEDITREPORT,
//     component: CustomReportSetting,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },

//   //

//   {
//     routePath: APPLICATION_ROUTES.AMAZONBUDGETPACER,
//     component: AMAZONBUDGETPACER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },

//   {
//     routePath: APPLICATION_ROUTES.KEYWORDREPORT,
//     component: KEYWORDREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMSCREATENEWCAMPAIGN,
//     component: AMSCREATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMSCREATEBULKCAMPAIGN,
//     component: AMSCREATEBulkNEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.AMSCREATEBULKAGROUPCAMPAIGN,
//     component: AMSCREATEBulkNEWAGROUPCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },

//   {
//     routePath: APPLICATION_ROUTES.AMSMETRICANALYZER,
//     component: AMSMETRICANALYZER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/amazon",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKIT,
//     component: BLINKITComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKIT,
//     component: BLINKITComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKIT,
//     component: BLINKITComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITCAMPAING,
//     component: BLINKITCAMPAIGNComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITNEGATIVEKEYWORD,
//     component: BLINKITNEGATIVEKEYWORD,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITREPORTCAMPAING,
//     component: BLINKITREPORTCAMPAIGNComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITRULES,
//     component: BLINKITRULES,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITCATEGORYREPORT,
//     component: BLINKITCATEGORYREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   // {
//   //   routePath: APPLICATION_ROUTES.BLINKITREPORTTARGET,
//   //   component: BLINKITTARGETREPORT,
//   //   isPrivate: true,
//   //   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   //   visibleAfterLogin: true,
//   //   sidebar: "/blinkit",
//   // },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITKEYWORDREPORT,
//     component: BLINKITKEYWORDREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   // {
//   //   routePath: APPLICATION_ROUTES.BLINKITCREATIVEREPORT,
//   //   component: BLINKITCREATIVEREPORT,
//   //   isPrivate: true,
//   //   accessRoles: [APP_ROLE.ADMIN,APP_ROLE.OWNER,APP_ROLE.ANALYST,APP_ROLE.MANAGER],
//   //   visibleAfterLogin: true,
//   //   sidebar: "/blinkit",
//   // },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITREVENUEREPORT,
//     component: BLINKITREVENUEREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITCREATENEWCAMPAIGN,
//     component: BLINKITCREATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTCREATENEWCAMPAIGN,
//     component: INSTAMARTCREATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTDUPLICATENEWCAMPAIGN,
//     component: INSTAMARTDUPLICATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },

//   {
//     routePath: APPLICATION_ROUTES.BLINKITFSNREPORT,
//     component: BLINKITFSNREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITSEARCHREPORT,
//     component: BLINKITSEARCHREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITPLACEMENTREPORT,
//     component: BLINKITPLACEMENTREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },

//   {
//     routePath: APPLICATION_ROUTES.BLINKITACTIONACTIVITY,
//     component: BLINKITACTIONACTIVITY,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.BLINKITBUDGETPACER,
//     component: BLINKITBUDGETPACER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/blinkit",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTO,
//     component: ZEPTOComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCATEGORYREPORT,
//     component: ZEPTOCATEGORYREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTORULES,
//     component: ZEPTORULES,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCAMPAIGNREPORT,
//     component: ZEPTOCAMPAIGNREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOKEYWORDREPORT,
//     component: ZEPTOKEYWORDREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCAMPAING,
//     component: ZeptoCAMPAIGNComponent,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOPRODUCTREPORT,
//     component: ZEPTOPRODUCTREPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOACTIONACTIVITY,
//     component: ZEPTOACTIONACTIVITY,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOCREATENEWCAMPAIGN,
//     component: ZEPTOCREATENEWCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },
//   {
//     routePath: APPLICATION_ROUTES.ZEPTOBUDGETPACER,
//     component: ZEPTOBUDGETPACER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/zepto",
//   },

//   // instamart
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART,
//     component: INSTAMART,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART,
//     component: INSTAMART_CAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTCAMPAIGNMANAGER,
//     component: INSTAMART_CAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART_CAMPAIGN_REPORT,
//     component: INSTAMART_CAMPAIGN_REPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART_KEYWORD,
//     component: INSTAMART_KEYWORD,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART_PRODUCT_REPORT,
//     component: INSTAMART_PRODUCT_REPORT,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART_ACTION_ACTIVITY,
//     component: INSTAMART_ACTION_ACTIVITY,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMART_BUDGET_PACER,
//     component: INSTAMART_BUDGET_PACER,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTRULES,
//     component: INSTAMARTRULES,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
//   {
//     routePath: APPLICATION_ROUTES.INSTAMARTEDITCAMPAIGN,
//     component: INSTAMARTEDITCAMPAIGN,
//     isPrivate: true,
//     accessRoles: [
//       APP_ROLE.ADMIN,
//       APP_ROLE.OWNER,
//       APP_ROLE.ANALYST,
//       APP_ROLE.MANAGER,
//     ],
//     visibleAfterLogin: true,
//     sidebar: "/instamart",
//   },
// ];

let availableRoutes= [
  
{
    routePath: APPLICATION_ROUTES.DASHBOARD,
    component: DASHBOARDComponent,
    isPrivate: true,
    accessRoles: [
      APP_ROLE.ADMIN,
      APP_ROLE.OWNER,
      APP_ROLE.ANALYST,
      APP_ROLE.MANAGER,
    ],
    visibleAfterLogin: true,
    sidebar: "/dashboard",
  },
];

// let platforms =[];
//  platforms = localStorage.getItem("platforms");
// platforms = JSON.parse(platforms)
// if(platforms) {
// platforms?.platform?.map((item) => {
//   if(item == 'flipkart') {
//     availableRoutes.push(...flipkartRoutes)
//   }
//   if(item == 'amazon') {
//     availableRoutes.push(...amazonRoutes)
//   }
//   if(item == 'blinkit') {
//     availableRoutes.push(...blinkitRoutes)
//   }
//   if(item == 'zepto') {
//     availableRoutes.push(...zeptoRoutes)
//   }
// })
// }

export default availableRoutes;
