export const AMAZON_ACCOUNTS = "/amazon/accounts";
export const AMAZON_BUYBOX_ACCOUNTS = "/amazon/getbuyBoxAccounts";
export const GET_AMAZON_PORTFOLIOLIST = "amazon/advertising/portfolio/list";
export const GET_AMAZON_ASINLIST = "amazon/advertising/asin/list";
export const REMOVE_AMAZON_NEGATIVE_KEYWORDS =
  "amazon/advertising/negativekeyword/remove";
export const AMAZON_BUDGET_SUMMARY = "/amazon_budget_pacer_summary";
export const AMAZON_DAILY_BUDGET_PACER = "/amazon_budget_pacer_daily";
export const AMAZON_BUDGET_PACER_UPDATE = "/amazon_budget_pacer";
export const brandDataListing = [
  {
    label: "Enfagrow A+",
    value: "1830184774214075",
    account_id: "1830184774214075",
    platform_id: "1830184774214075",
  },
  {
    label: "Dettol",
    value: "3214432698219643",
    account_id: "3214432698219643",
    platform_id: "3214432698219643",
  },
  {
    label: "Durex",
    value: "908441297373339",
    account_id: "908441297373339",
    platform_id: "908441297373339",
  },
  {
    label: "Veet",
    value: "4429017988501263",
    account_id: "4429017988501263",
    platform_id: "4429017988501263",
  },
  {
    label: "Moov",
    value: "909206879610505",
    account_id: "909206879610505",
    platform_id: "909206879610505",
  },
];
export const portfolioListing = [
  {
    label: "Portfolio1",
  },
  {
    label: "Portfolio2",
  },
  {
    label: "Portfolio3",
  },
  {
    label: "Portfolio4",
  },
];

export const amazonPortfolioheader = [
  {
    id: 2,
    title: "Status",
    value: "state",
    checked: true,
    showCol: true,
    show: false,
    type: "single",
    subTitles: [],
    disable: true,
  },
  {
    id: 1,
    title: "Portfolio Names",
    value: "name",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
    disable: true,
  },
  {
    id: 6,
    title: "Campaign Count",
    value: "count",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 3,
    title: "Budget",
    value: "budget_amount",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 4,
    title: "Budget Start Date",
    value: "budget_start_date",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 5,
    title: "Budget End Date",
    value: "budget_end_date",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 10,
    title: "Spend",
    value: "spend",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
  },
  {
    id: 12,
    title: "Orders",
    value: "orders",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 13,
    title: "Sales",
    value: "sales",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 15,
    title: "ROAS",
    value: "roas",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 7,
    title: "Impressions",
    value: "impressions",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 8,
    title: "Clicks",
    value: "clicks",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 9,
    title: "CTR",
    value: "ctr",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 11,
    title: "CPC",
    value: "cpc",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 14,
    title: "ACOS",
    value: "acos",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 16,
    title: "NTB Orders",
    value: "ntb_orders",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
  },
  {
    id: 17,
    title: "% of orders NTB",
    value: "ntb_orders_perc",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
  },
  {
    id: 18,
    title: "NTB sales",
    value: "ntb_sales",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
  },
  {
    id: 19,
    title: "% of sales NTB",
    value: "ntb_sales_perc",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
  },

  {
    id: 20,
    title: "Viewable Impressions",
    value: "viewable_impressions",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
  },
  //   {
  //     id: 21,
  //     title: "VCPM",
  //     value: "total_viewable_impressions",
  //     checked: false,
  //     show: false,
  //     showCol: false,
  //     type: "single",
  //     subTitles: [],
  //   },
];

export const LIMIT = 10;
export const amazonAsinheader = [
  {
    id: 18,
    title: "Status",
    value: "state",
    checked: true,
    show: false,
    showCol: true,
    type: "single",
    subTitles: [],
    disable: true,
  },

  {
    id: 1,
    title: "ASIN Name",
    value: "product_id",
    checked: true,
    show: true,
    showCol: true,
    disabled: true,
    type: "single",
    subTitles: [],
    disable: true,
  },
  {
    id: 4,
    title: "Campaign Name",
    value: "campaign_name",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 5,
    title: "Ad Group",
    value: "ad_group_name",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 18,
    title: "MRP",
    value: "price",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
    columnType: "dsa"
  },
  {
    id: 19,
    title: "Review",
    value: "review",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
    columnType: "dsa"
  },
  {
    id: 20,
    title: "Rating",
    value: "rating",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
    columnType: "dsa"
  },
  {
    id: 21,
    title: "Availability",
    value: "availability",
    checked: false,
    show: true,
    showCol: false,
    type: "single",
    subTitles: [],
    columnType: "dsa"
  },
  
  {
    id: 14,
    title: "Spend",
    value: "spend",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 16,
    title: "Orders",
    value: "orders",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 8,
    title: "Sales",
    value: "sales",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  // {
  //   id: 2,
  //   title: "ASIN ID",
  //   value: "product_id",
  //   checked: false,
  //   show: false,
  //   showCol: false,
  //   type: "single",
  //   subTitles: [],
  // },

  {
    id: 9,
    title: "ROAS",
    value: "roas",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 11,
    title: "Impressions",
    value: "impressions",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  // {
  //   id: 6,
  //   title: "Status",
  //   value: "status",
  //   checked: true,
  //   show: false,
  //   showCol: true,
  //   type: "single",
  //   subTitles: [],
  // },
  // {
  //   id: 7,
  //   title: "Category",
  //   value: "product",
  //   checked: false,
  //   show: false,
  //   showCol: false,
  //   type: "single",
  //   subTitles: [],
  // },

  // {
  //   id: 10,
  //   title: "Conversion rate",
  //   value: "conversion",
  //   checked: false,
  //   show: true,
  //   showCol: false,
  //   type: "single",
  //   subTitles: [],
  // },

  {
    id: 12,
    title: "Clicks",
    value: "clicks",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 13,
    title: "CTR",
    value: "ctr",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 15,
    title: "CPC",
    value: "cpc",
    checked: false,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 17,
    title: "ACOS",
    value: "acos",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 3,
    title: "Portfolio",
    value: "portfolio_name",
    checked: false,
    show: false,
    showCol: false,
    type: "single",
    subTitles: [],
  },
];

export const amazonCampaignheader = [
  {
    id: 1,
    title: "Campaign",
    value: "campaign_name",
    checked: true,
    show: true,
    showCol: true,
    disabled: true,
    type: "single",
    subTitles: [],
    disable: true,
  },

  {
    id: 2,
    title: "CTR",
    value: "ctr",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 3,
    title: "Sales",
    value: "sales",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 4,
    title: "Orders",
    value: "units_sold",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 6,
    title: "ROAS",
    value: "roas",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 7,
    title: "Clicks",
    value: "clicks",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 7,
    title: "Spends",
    value: "spend",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 8,
    title: "Impressions",
    value: "impressions",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 9,
    title: "CPC",
    value: "cpc",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 10,
    title: "ACOS",
    value: "acos",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
];

export const amazonMetricTableHeader = [
  {
    id: 1,
    title: "Campaign",
    value: "campaign_name",
    showSort: false,
  },
  {
    id: 2,
    title: "CTR",
    value: "CTR",
    showSort: true,
  },

  {
    id: 3,
    title: "Sales",
    value: "sales",
    showSort: true,
  },
  {
    id: 4,
    title: "Orders",
    value: "unit_sold",
    showSort: true,
  },

  {
    id: 6,
    title: "ROAS",
    value: "roas",
    showSort: true,
  },
  {
    id: 7,
    title: "Clicks",
    value: "clicks",
    showSort: true,
  },
  {
    id: 7,
    title: "Spends",
    value: "spends",
    showSort: true,
  },
];
export const campaigndata = [
  {
    campaign_name: "Campaign 1",
    date: "29-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    campaign_name: "Campaign 2",
    date: "29-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    campaign_name: "Campaign 3",
    date: "29-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    campaign_name: "Campaign 4",
    date: "29-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    campaign_name: "Campaign 5",
    date: "29-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
];

export const amazonMetricTableAdgroupHeader = [
  {
    id: 1,
    title: "Ad Group",
    value: "ad_group_name",
    showCol: false,
  },

  {
    id: 2,
    title: "Campaign",
    value: "campaign_name",
    showCol: false,
  },
  {
    id: 10,
    title: "CTR",
    value: "ctr",
    showCol: true,
  },
  {
    id: 4,
    title: "ROAS",
    value: "roas",
    showCol: true,
  },
  {
    id: 4,
    title: "ACOS",
    value: "acos",
    showCol: true,
  },
  {
    id: 5,
    title: "Clicks",
    value: "clicks",
    showCol: true,
  },
  {
    id: 6,
    title: "Spends",
    value: "spend",
    showCol: true,
  },
  {
    id: 7,
    title: "Impressions",
    value: "impressions",
    showCol: true,
  },
  {
    id: 8,
    title: "Orders",
    value: "orders",
    showCol: true,
  },
  {
    id: 9,
    title: "CPC",
    value: "cpc",
    showCol: true,
  },
  {
    id: 13,
    title: "Sales",
    value: "sales",

    showCol: true,
  },
];
export const adgroupdata = [
  {
    adgroup: "AdGroup",
    addate: "29-02-2023",
    campaign_name: "Campaign",
    date: "29-02-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    adgroup: "AdGroup",
    addate: "29-02-2023",
    campaign_name: "Campaign",
    date: "21-02-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    adgroup: "AdGroup",
    addate: "29-02-2023",
    campaign_name: "Campaign",
    date: "21-02-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    adgroup: "AdGroup",
    addate: "29-02-2023",
    campaign_name: "Campaign",
    date: "21-02-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    adgroup: "AdGroup",
    addate: "29-02-2023",
    campaign_name: "Campaign",
    date: "21-02-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
];

export const amazonMetricTableKeywordHeader = [
  {
    id: 1,
    title: "Keyword",
    value: "keyword_text",
    showSort: false,
  },
  {
    id: 2,
    title: "Ad Group",
    value: "ad_group_name",
    showSort: false,
  },

  {
    id: 3,
    title: "Campaign",
    value: "campaign_name",
    showSort: false,
  },

  {
    id: 10,
    title: "CTR",
    value: "ctr",
    showCol: true,
  },
  {
    id: 11,
    title: "ROAS",
    value: "roas",
    showCol: true,
  },
  {
    id: 4,
    title: "ACOS",
    value: "acos",
    showCol: true,
  },
  {
    id: 5,
    title: "Clicks",
    value: "clicks",
    showCol: true,
  },
  {
    id: 6,
    title: "Spends",
    value: "spend",
    showCol: true,
  },
  {
    id: 7,
    title: "Impressions",
    value: "impressions",
    showCol: true,
  },
  {
    id: 8,
    title: "Orders",
    value: "orders",
    showCol: true,
  },
  {
    id: 9,
    title: "CPC",
    value: "cpc",
    showCol: true,
  },
  {
    id: 13,
    title: "Sales",
    value: "sales",

    showCol: true,
  },
];
export const keyworddata = [
  {
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
];

export const amazonMetricTableAsinHeader = [
  {
    id: 1,
    title: "ASINS",
    value: "product_id",
    bgColor: true,
    showCol: true,
    size: "l",
  },
  // {
  //   id: 2,
  //   title: "Keyword",
  //   value: "keyword",
  //   bgColor: true,
  //   showCol: true,
  //   size: "l",
  // },
  {
    id: 3,
    title: "Ad Group",
    value: "ad_group_name",
    bgColor: true,
    showCol: true,
    size: "xl",
  },

  {
    id: 4,
    title: "Campaign",
    value: "campaign_name",
    bgColor: true,
    showCol: true,
    size: "xl",
  },
  {
    id: 5,
    title: "CTR",
    value: "ctr",
    dynamic: true,
    showCol: true,
  },

  // {
  //   id: 6,
  //   title: "Absolute Change",
  //   value: "absolute_change",
  //   showCol: true,
  // },
  // {
  //   id: 7,
  //   title: "Percentage Change",
  //   value: "percentagechange",
  //   showCol: true,
  // },
  {
    id: 8,
    title: "Impressions",
    value: "impressions",
    showCol: true,
  },
  {
    id: 8,
    title: "ROAS",
    value: "roas",
    showCol: true,
  },
  {
    id: 9,
    title: "Clicks",
    value: "clicks",
    showCol: true,
  },
  {
    id: 10,
    title: "Spends",
    value: "spend",
    showCol: true,
  },
  { id: 11, title: "ACOS", value: "acos", showCol: true },
  { id: 12, title: "CPC", value: "cpc", showCol: true },
  { id: 13, title: "Orders", value: "orders", showCol: true },
  { id: 14, title: "Sales", value: "sales", showCol: true },
];
export const asinsdata = [
  {
    asins: "ASIN 1",
    asindate: "28-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN 1",
    asindate: "28-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN 1",
    asindate: "28-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
];
export const amazonMetricTablePlacementHeader = [
  {
    id: 1,
    title: "Placement",
    value: "placement",
    bgColor: true,
    showCol: true,
    size: "l",
  },
  // {
  //   id: 5,
  //   title: "ASINS",
  //   value: "asin",
  //   bgColor: true,
  //   showCol: true,
  //   size: "l",
  // },
  // {
  //   id: 4,
  //   title: "Keyword",
  //   value: "keyword",
  //   bgColor: true,
  //   showCol: true,
  //   size: "l",
  // },
  // {
  //   id: 3,
  //   title: "Ad Group",
  //   value: "adgroup",
  //   bgColor: true,
  //   showCol: true,
  //   size: "xl",
  // },

  {
    id: 5,
    title: "Campaign",
    value: "campaign_name",
    bgColor: true,
    showCol: true,
    size: "xl",
  },
  // {
  //   id: 6,
  //   title: "Campaign bidding strategy",
  //   value: "campaign_bidding_stratergy",
  //   showCol: true,
  // },
  {
    id: 7,
    title: "Impressions",
    value: "impressions",
    showCol: true,
  },
  {
    id: 8,
    title: "Clicks",
    value: "clicks",
    showCol: true,
  },
  {
    id: 9,
    title: "CTR",
    value: "ctr",
    showCol: true,
  },
  {
    id: 10,
    title: "Spend",
    value: "spend",
    showCol: true,
  },
  {
    id: 11,
    title: "CPC",
    value: "cpc",
    showCol: true,
  },
  {
    id: 12,
    title: "Orders",
    value: "conversion",

    showCol: true,
  },
  {
    id: 13,
    title: "Sales",
    value: "sales",

    showCol: true,
  },
  {
    id: 14,
    title: "ACOS",
    value: "acos",

    showCol: true,
  },
  {
    id: 15,
    title: "ROAS",
    value: "roas",

    showCol: true,
  },
];
export const placementdata = [
  {
    placement: "Placement",
    placementdate: "23-02-2023",
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    placement: "Placement  ",
    placementdate: "23-02-2023",
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    placement: "Placement ",
    placementdate: "23-02-2023",
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    placement: "Placement",
    placementdate: "23-02-2023",
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
  {
    placement: "Placement ",
    placementdate: "23-02-2023",
    asins: "ASIN ",
    asindate: "23-03-2023",
    keyword: "Keyword",
    kdate: "26-03-2023",
    adgroup: "AdGroup",
    adate: "26-03-2023",
    campaign_name: "Campaign",
    date: "26-03-2023",
    CTR: "0.1% ",
    CTR1: "0.8%",
    absolute_change: "0.1%",
    percentagechange: "3%",
    roas: "20",
    clicks: "2234",
    spends: "57889",
  },
];

export const CommonScreenTableHeader = [
  {
    id: 1,
    title: "Platform",
    value: "platform",
    showSort: true,
  },

  {
    id: 2,
    title: "Spend",
    value: "spend",
    showSort: true,
  },
  {
    id: 3,
    title: "Sales",
    value: "sales",
    showSort: true,
  },

  {
    id: 4,
    title: "Orders",
    value: "orders",
    showSort: true,
  },
  {
    id: 5,
    title: "ROAS",
    value: "roas",
    showSort: true,
  },

  {
    id: 6,
    title: "Impressions",
    value: "impressions",
    showSort: true,
  },
  {
    id: 8,
    title: "Clicks",
    value: "clicks",
    showSort: true,
  },
  {
    id: 7,
    title: "CTR",
    value: "ctr",
    showSort: true,
  },
  {
    id: 9,
    title: "CPC",
    value: "cpc",
    showSort: true,
  },
  {
    id: 10,
    title: "AOV",
    value: "aov",
    showSort: true,
  },
];
export const CommonScreenTabledata = [
  {
    image: "/assets/images/flipkartFavicon.png",
    spend: "1234",
    rise: "122",
    percentage: "12%",
    sales: "23",
    revenue: "43",
    orders: "87",
    roas: "7587",
    scr: "33",
    aov: "0.3",
    ctr: "0.1",
  },
];
export const CommonScreenZeptoTabledata = [
  {
    image: "/assets/images/zepto-icon.png",
    spend: "1234",
    rise: "122",
    percentage: "12%",
    sales: "23",
    revenue: "43",
    orders: "87",
    roas: "7587",
    scr: "33",
    aov: "0.3",
    ctr: "0.1",
  },
  // {
  //   image: "/assets/images/zepto.svg",
  //   spend: "1234",
  //   rise: "122",
  //   percentage: "12%",
  //   sales: "23",
  //   revenue: "43",
  //   orders: "87",
  //   roas: "7587",
  //   scr: "33",
  //   aov: "0.3",
  //   ctr: "0.1",
  // },
  // {
  //   image: "assets/images/blinkit.svg",
  //   spend: "1234",
  //   rise: "122",
  //   percentage: "12%",
  //   sales: "23",
  //   revenue: "43",
  //   orders: "87",
  //   roas: "7587",
  //   scr: "33",
  //   aov: "0.3",
  //   ctr: "0.1",
  // },
];
export const CommonScreenSwiggyTabledata = [
  {
    image: "/assets/images/swiggy.svg",
    spend: "1234",
    rise: "122",
    percentage: "12%",
    sales: "23",
    revenue: "43",
    orders: "87",
    roas: "7587",
    scr: "33",
    aov: "0.3",
    ctr: "0.1",
  },
];
export const CommonScreenBlinkiTabledata = [
  {
    image: "/assets/images/blinkitFavicon.ico",
    spend: "1234",
    rise: "122",
    percentage: "12%",
    sales: "23",
    revenue: "43",
    orders: "87",
    roas: "7587",
    scr: "33",
    aov: "0.3",
    ctr: "0.1",
  },
];
export const CommonScreenTablefooterdata = [
  {
    spend: "1234",
    rise: "122",
    percentage: "12%",
    sales: "23",
    revenue: "43",
    orders: "87",
    roas: "7587",
    scr: "33",
    aov: "0.3",
    ctr: "0.1",
  },
];
