export const campaignBlinkitHeaders = [
    {
        id: 1,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];
export const campaignHeaders = [
    {
        id: 1,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];


export const adgroupHeaders = [
    {
        id: 1,
        title: "Adgroup Name",
        value: "ad_group_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];

export const keywordHeaders = [
    {
        id: 0,
        title: "Keyword",
        value: "keyword",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];
export const blinkitKeywordHeaders = [
    {
        id: 0,
        title: "Keyword",
        value: "keyword",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },

    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];

export const blinkitCategoryHeaders = [
    {
        id: 0,
        title: "Category",
        value: "category_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },

    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];

export const categoryHeaders = [
    {
        id: 0,
        title: "Category",
        value: "category",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },

    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];
export const productHeaders = [
    {
        id: 0,
        title: "Product Name",
        value: "product_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
]

export const fsnHeaders = [
    {
        id: 0,
        title: "Product Name",
        value: "product_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 1,
        title: "Adgroup Name",
        value: "adgroup_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 2,
        title: "Campaign Name",
        value: "campaign_name",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 3,
        title: "Campaign Type",
        value: "segment",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 4,
        title: "Account",
        value: "platform_id",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    },
    {
        id: 5,
        title: "Platform",
        value: "platform",
        checked: true,
        show: true,
        showCol: true,
        type: "single",
        subTitles: [],
    }
];