export const zeptoCampaign = [
  {
    id: 30,
    title: "Status",
    value: "status",
    checked: true,
    showCol: true,
    show: false,
    type: "single",
    subTitles: [],
    disable:true
  },
  {
    id: 1,
    title: "Campaign Name",
    value: "campaign_name",
    checked: true,
    disable: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 2,
    title: "Campaign Type",
    value: "campaign_type",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 16,
    title: "Daily Budget",
    value: "campaign_budget",
    checked: true,
    show: false,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 3,
    title: "Added Tag",
    value: "tag_id",
    checked: true,
    showCol: true,
    show: false,
    type: "single",
    subTitles: [],
  },
  {
    id: 5,
    title: "Spend",
    value: "spend",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 11,
    title: "Sales",
    value: "revenues",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 10,
    title: "Orders",
    value: "orders",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 9,
    title: "ATC",
    value: "add2cart",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 12,
    title: "ROAS",
    value: "roas",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 4,
    title: "Impressions",
    value: "impressions",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 6,
    title: "Clicks",
    value: "clicks",
    checked: true,
    showCol: true,
    show: true,
    type: "single",
    subTitles: [],
  },

  {
    id: 7,
    title: "CTR",
    value: "ctr",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },

  // {
  //   id: 8,
  //   title: "CPM",
  //   value: "cpm",
  //   checked: true,
  //   show: true,
  //   showCol: true,
  //   type: "single",
  //   subTitles: [],
  // },

  {
    id: 13,
    title: "CPM",
    value: "cpm",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
  {
    id: 14,
    title: "CPC",
    value: "cpc",
    checked: true,
    show: true,
    showCol: true,
    type: "single",
    subTitles: [],
  },
];
